'use strict';

const fs = require('fs');
const path = require('path');
const test = require('node:test');
const assert = require('node:assert/strict');

const root = path.join(__dirname, '..');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const installer = fs.readFileSync(path.join(root, 'build', 'installer.nsh'), 'utf8');
const legacyCleanupBytes = fs.readFileSync(path.join(root, 'build', 'cleanup-legacy-cli.ps1'));
const legacyCleanup = legacyCleanupBytes.toString('utf8');

test('packages only required Windows x64 runtime files with maximum compression', () => {
  const build = packageJson.build;
  assert.equal(build.asar, true);
  assert.equal(build.compression, 'maximum');
  assert.deepEqual(build.electronLanguages, ['zh-CN']);
  assert.deepEqual(build.win.target, [{ target: 'nsis', arch: ['x64'] }]);
  assert.ok(build.files.includes('assets/cat-processed/**/*'));
  assert.ok(build.files.includes('assets/head/**/*'));
  assert.ok(!build.files.includes('build/face.ico'));
  assert.equal(build.win.icon, 'dist/cli/assets/forcome.ico');
  assert.equal(build.nsis.installerIcon, 'dist/cli/assets/forcome.ico');
  assert.equal(build.nsis.uninstallerIcon, 'dist/cli/assets/forcome.ico');
  assert.equal(build.nsis.installerHeaderIcon, 'dist/cli/assets/forcome.ico');
  assert.ok(build.extraResources.some((resource) => resource.from === 'dist/cli/runtime' && resource.to === 'forcome-cli/runtime'));
  assert.ok(build.extraResources.some((resource) => resource.from === 'dist/cli/cli' && resource.to === 'forcome-cli/cli'));
  assert.ok(build.extraResources.some((resource) => resource.from === 'dist/cli/ForcomeAiTray.exe' && resource.to === 'forcome-cli/ForcomeAiTray.exe'));
  assert.ok(build.files.includes('!**/*.map'));
  assert.ok(build.files.includes('!node_modules/exceljs/dist/**/*'));
  assert.ok(!build.files.includes('assets/**/*'));
  assert.ok(!build.files.includes('assets/cat/**/*'));
  assert.ok(build.asarUnpack.includes('assets/cat-processed/**'));
  assert.ok(!build.asarUnpack.includes('assets/cat/**'));
});

test('uses a standard per-user installer, preserves manual legacy cleanup, and keeps silent updates lightweight', () => {
  const nsis = packageJson.build.nsis;
  assert.equal(nsis.oneClick, false);
  assert.equal(nsis.allowToChangeInstallationDirectory, true);
  assert.equal(nsis.perMachine, false);
  assert.equal(nsis.createDesktopShortcut, true);
  assert.equal(nsis.createStartMenuShortcut, true);
  assert.equal(nsis.menuCategory, '康康熊桌宠');
  assert.equal(nsis.runAfterFinish, true);
  assert.equal(nsis.deleteAppDataOnUninstall, false);
  assert.match(installer, /!undef APP_FILENAME/);
  assert.match(installer, /!define APP_FILENAME "康康Pet"/);
  assert.match(installer, /!define KANGKANGPET_SUFFIX "\\康康Pet"/);
  assert.match(installer, /!define LEGACY_KANGKANGPET_SUFFIX "\\kangkangpet"/);
  assert.match(installer, /!macro customInit/);
  assert.match(installer, /\$\{StdUtils\.GetParameter\} \$R0 "D" ""/);
  assert.match(installer, /StrCpy \$INSTDIR \$R0/);
  assert.match(installer, /StrCpy \$INSTDIR "\$LOCALAPPDATA\\Programs"/);
  assert.match(installer, /!macro customInit[\s\S]*?Call EnsureWritableKangKangPetInstallDir/);
  assert.match(installer, /Function \.onVerifyInstDir/);
  assert.match(installer, /Function NormalizeKangKangPetInstallDir/);
  assert.match(installer, /Function PathContains/);
  assert.match(installer, /Function EnsureWritableKangKangPetInstallDir/);
  assert.match(installer, /StrCpy \$R1 "\$PROGRAMFILES64"/);
  assert.match(installer, /StrCpy \$R1 "\$WINDIR"/);
  assert.match(installer, /检测到选择了 Windows 受保护目录/);
  assert.match(installer, /StrCmp \$R4 "\$\{LEGACY_KANGKANGPET_SUFFIX\}" replaceLegacy appendSuffix/);
  assert.match(installer, /Call NormalizeKangKangPetInstallDir/);
  assert.match(installer, /!ifndef BUILD_UNINSTALLER/);
  assert.match(installer, /!macro customCheckAppRunning/);
  assert.match(installer, /!macro customPageAfterChangeDir/);
  assert.match(installer, /PageCallbacks LegacyCliChoicePageShow LegacyCliChoicePageLeave/);
  assert.match(installer, /检测到电脑中存在旧版FORCOME AI CLI。/);
  assert.match(installer, /NSD_CreateButton\} 20u 70u 120u 28u "卸载旧版"/);
  assert.match(installer, /NSD_CreateButton\} 160u 70u 120u 28u "保留旧版"/);
  assert.match(installer, /!macro customInstall/);
  assert.match(installer, /taskkill \/F \/T \/IM/);
  assert.match(installer, /cleanup-legacy-cli\.ps1/);
  assert.match(installer, /-AuditOnly/);
  assert.doesNotMatch(installer, /MB_YESNO\|MB_ICONQUESTION/);
  assert.doesNotMatch(installer, /选择“是”|选择“否”/);
  assert.match(installer, /StrCpy \$LegacyCliChoice "uninstall"/);
  assert.match(installer, /StrCpy \$LegacyCliChoice "keep"/);
  assert.match(installer, /StrCpy \$SkipEmbeddedCli 1/);
  assert.match(installer, /已保留内置 FORCOME AI CLI 文件；运行时将避免与独立安装版连接器同时运行。/);
  assert.doesNotMatch(installer, /RMDir \/r "\$INSTDIR\\resources\\forcome-cli"/);
  assert.match(installer, /IfSilent legacyCliSilentSkip/);
  assert.match(legacyCleanup, /if \(\$audit\.Count -gt 0\) \{ exit 10 \}/);
  assert.deepEqual([...legacyCleanupBytes.subarray(0, 3)], [0xef, 0xbb, 0xbf]);
  assert.match(legacyCleanup, /ForcomeAI-Connector/);
  assert.match(legacyCleanup, /ForcomeAI-Tray/);
  assert.match(legacyCleanup, /npm\.cmd/);
  assert.match(legacyCleanup, /@forcome\[\\\\\/\]ai-cli/);
  assert.match(legacyCleanup, /ForcomeAI\\cli/);
  assert.match(legacyCleanup, /保留 \.lobehub 登录凭据/);
  assert.doesNotMatch(legacyCleanup, /Remove-Item[^\n]+credentials\.json/i);
  assert.match(installer, /Preserving local reminder, calendar, note, and settings data in AppData/);
  assert.doesNotMatch(installer, /KangKangSelectDefaultInstallDrive|Get-PSDrive|MUI_PAGE_DIRECTORY|CreateShortCut/);
  assert.doesNotMatch(installer, /StrCpy \$INSTDIR "\$PROGRAMFILES64"/);
});
